# Paths
paths:
  raw_data: "data/raw/"
  processed_data: "data/processed/"

# Data
data:
  dataset_name: "tg_ens_mean_0.25deg_reg_1950-1964_v31.0e"
  latitude_column: "latitude"
  longitude_column: "langitude"
  timestamp: "time"
  weather_name: "variable"
  URL: "https://knmi-ecad-assets-prd.s3.amazonaws.com/ensembles/data/Grid_0.25deg_reg_ensemble/tg_ens_mean_0.25deg_reg_1950-1964_v31.0e.nc"

  



